language: node_js
node_js:
  - 'lts/*'
  - 13
services: redis
sudo: false
script:
  - yarn run travis
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
